LACTOSE_KEYWORDS = [
    "milk",
    "cream",
    "cheese",
    "butter",
    "yogurt",
    "yoghurt",
    "whey",
    "casein",
    "lactose",
    "ghee",
    "kefir",
    "custard",
    "brie",
    "cheddar",
    "mozzarella",
    "parmesan",
    "ricotta",
    "mascarpone",
    "gouda",
    "feta",
    "camembert",
    "gruyere",
    "halloumi",
    "quark",
    "creme fraiche",
    "half-and-half",
    "half and half",
    "chocolate",
]

LACTOSE_FREE_OVERRIDE_PHRASES = [
    "lactose free",
    "lactose-free",
    "dairy free",
    "dairy-free",
    "non-dairy",
    "non dairy",
    "almond milk",
    "oat milk",
    "soy milk",
    "rice milk",
    "coconut milk",
    "hemp milk",
    "cashew milk",
    "macadamia milk",
    "pea milk",
    "coconut cream",
    "oat cream",
    "soy cream",
    "peanut butter",
    "almond butter",
    "cashew butter",
    "sunflower butter",
    "hazelnut butter",
    "nut butter",
    "seed butter",
    "cocoa butter",
    "vegan butter",
    "vegan cheese",
    "vegan cream",
    "vegan milk",
    "vegan chocolate",
    "dark chocolate",
    "dairy-free chocolate",
    "dairy free chocolate",
]

GLUTEN_KEYWORDS = [
    "wheat",
    "flour",
    "pasta",
    "bread",
    "barley",
    "rye",
    "malt",
    "semolina",
    "spelt",
    "couscous",
    "bulgur",
    "farro",
    "durum",
    "triticale",
    "kamut",
    "einkorn",
    "emmer",
    "noodle",
    "spaghetti",
    "linguine",
    "fettuccine",
    "penne",
    "rigatoni",
    "lasagna",
    "lasagne",
    "orzo",
    "vermicelli",
    "udon",
    "ramen",
    "tortilla",
    "pita",
    "lavash",
    "crouton",
    "biscuit",
    "cracker",
    "pretzel",
    "wafer",
    "soy sauce",
    "teriyaki sauce",
    "worcestershire",
    "panko",
    "matzo",
    "phyllo",
    "filo",
    "puff pastry",
    "shortcrust",
]

GLUTEN_FREE_OVERRIDE_PHRASES = [
    "gluten free",
    "gluten-free",
    "rice flour",
    "almond flour",
    "coconut flour",
    "tapioca flour",
    "cassava flour",
    "chickpea flour",
    "corn flour",
    "potato flour",
    "buckwheat flour",
    "teff flour",
    "sorghum flour",
    "arrowroot flour",
    "oat flour",
    "rice noodle",
    "glass noodle",
    "cellophane noodle",
    "rice vermicelli",
    "shirataki",
    "rice pasta",
    "corn pasta",
    "chickpea pasta",
    "lentil pasta",
    "quinoa pasta",
    "corn tortilla",
    "cassava tortilla",
    "rice cracker",
    "corn cracker",
    "seed cracker",
    "rice bread",
    "rice biscuit",
]

NON_VEGETARIAN_KEYWORDS = [
    "meat",
    "beef",
    "pork",
    "chicken",
    "turkey",
    "lamb",
    "veal",
    "duck",
    "goose",
    "venison",
    "bison",
    "boar",
    "rabbit",
    "quail",
    "pheasant",
    "bacon",
    "ham",
    "salami",
    "pepperoni",
    "prosciutto",
    "pancetta",
    "chorizo",
    "sausage",
    "hot dog",
    "hotdog",
    "bratwurst",
    "mortadella",
    "pastrami",
    "bresaola",
    "lard",
    "suet",
    "dripping",
    "fish",
    "salmon",
    "tuna",
    "cod",
    "haddock",
    "tilapia",
    "trout",
    "halibut",
    "sea bass",
    "mackerel",
    "sardine",
    "anchovy",
    "anchovies",
    "herring",
    "snapper",
    "swordfish",
    "mahi",
    "catfish",
    "carp",
    "shrimp",
    "prawn",
    "lobster",
    "crab",
    "crayfish",
    "scallop",
    "oyster",
    "clam",
    "mussel",
    "squid",
    "octopus",
    "calamari",
    "cuttlefish",
    "abalone",
    "cockle",
    "whelk",
    "seafood",
    "shellfish",
    "caviar",
    "roe",
    "gelatin",
    "gelatine",
    "bone broth",
    "worcestershire",
    "dashi",
    "bonito",
    "katsuobushi",
]

VEGETARIAN_OVERRIDE_PHRASES = [
    "vegetarian",
    "veggie",
    "meatless",
    "meat-free",
    "plant-based",
    "plant based",
    "vegan",
    "mock chicken",
    "mock duck",
    "mock beef",
    "mock pork",
    "mock meat",
    "imitation crab",
    "vegan sausage",
    "vegan bacon",
    "vegan ham",
    "vegan chorizo",
    "quorn",
    "seitan",
    "tempeh",
    "oyster mushroom",
    "soy chorizo",
    "soy sausage",
]

NON_VEGAN_KEYWORDS = NON_VEGETARIAN_KEYWORDS + [
    "milk",
    "cream",
    "cheese",
    "butter",
    "yogurt",
    "yoghurt",
    "whey",
    "casein",
    "lactose",
    "ghee",
    "kefir",
    "custard",
    "brie",
    "cheddar",
    "mozzarella",
    "parmesan",
    "ricotta",
    "mascarpone",
    "gouda",
    "feta",
    "camembert",
    "gruyere",
    "halloumi",
    "quark",
    "creme fraiche",
    "half-and-half",
    "half and half",
    "white chocolate",
    "egg",
    "honey",
    "beeswax",
    "royal jelly",
    "propolis",
    "tallow",
    "lanolin",
    "isinglass",
    "carmine",
    "cochineal",
    "shellac",
    "albumin",
    "collagen",
]

VEGAN_OVERRIDE_PHRASES = [
    "vegan",
    "plant-based",
    "plant based",
    "almond milk",
    "oat milk",
    "soy milk",
    "rice milk",
    "coconut milk",
    "hemp milk",
    "cashew milk",
    "macadamia milk",
    "pea milk",
    "coconut cream",
    "oat cream",
    "soy cream",
    "peanut butter",
    "almond butter",
    "cashew butter",
    "sunflower butter",
    "hazelnut butter",
    "nut butter",
    "seed butter",
    "cocoa butter",
    "mock chicken",
    "mock duck",
    "mock beef",
    "mock pork",
    "mock meat",
    "vegan sausage",
    "vegan bacon",
    "vegan ham",
    "vegan chorizo",
    "vegan cheese",
    "vegan butter",
    "vegan cream",
    "vegan milk",
    "vegan chocolate",
    "soy chorizo",
    "soy sausage",
    "dairy-free chocolate",
    "dairy free chocolate",
    "oyster mushroom",
    "eggplant",
]
