import json
from datetime import datetime

from openai import OpenAI

from engines.MealPlanner import MealPlanner
from models import MealPlanningEnvironment


class LLMMealPlanner(MealPlanner):
    def __init__(
        self,
        meal_planning_environment: MealPlanningEnvironment,
        llm_client: OpenAI,
        model_name: str,
        prompt_filepath: str,
    ):
        """
        The `LLMMealPlanner` class is an implementation of the `MealPlanner` abstract class that uses a large language
        model (LLM) to generate a meal plan. The LLM is prompted with detailed information about the available recipes,
        the user's pantry stock, and their preferences, and is tasked with selecting an optimal combination of recipes
        for the week.

        :param meal_planning_environment: the meal planning environment containing recipes, pantry, and user preferences
        :type meal_planning_environment: MealPlanningEnvironment
        :param llm_client: the OpenAI client used to interact with the LLM
        :type llm_client: OpenAI
        :param model_name: the name of the LLM model to use
        :type model_name: str
        :param prompt_filepath: the file path to the text file containing the prompt template for the LLM
        :type prompt_filepath: str
        """

        super().__init__(meal_planning_environment)

        self.llm_client = llm_client
        self.model_name = model_name

        with open(prompt_filepath, "r", encoding="utf-8") as prompt:
            self.prompt = prompt.read()

        # add available recipes, pantry stock, and user preferences to the prompt in a structured format

        self.prompt += "\n---\n\nAVAILABLE RECIPES:\n\n"

        for index, recipe in enumerate(self.recipes):
            # remove recipe instructions from the prompt to avoid increasing the context window unnecessarily, since the instructions are of no use to the planner

            recipe_without_instructions = recipe.to_dict().copy()

            del recipe_without_instructions["instructions"]

            self.prompt += f"{index}: {recipe_without_instructions}\n"

        self.prompt += "\n---\n\nPANTRY STOCK:\n\n"

        pantry_stock = self.meal_planning_environment.pantry.stock
        days_until_expiry = self.meal_planning_environment.pantry.get_days_until_expiry(datetime.now())

        for ingredient in self.meal_planning_environment.pantry.ingredients:
            quantity = pantry_stock.get(ingredient.name, 0)

            self.prompt += (
                f"{ingredient.name}: {quantity}g (expires in {days_until_expiry.get(ingredient.name, 0)} days)\n"
            )

        self.prompt += "\n---\n\nINGREDIENT COSTS (€/100g):\n\n"

        for ingredient_name, cost in self.ingredient_costs.items():
            self.prompt += f"{ingredient_name}: {cost}\n"

        self.prompt += "\n---\n\nUSER PREFERENCES:\n\n"

        for preference, value in self.preferences.to_dict().items():
            self.prompt += f"{preference}: {value}\n"

    def generate_meal_plan(self) -> tuple[list[int], float]:
        """
        Generates a meal plan by prompting a large language model with the provided information about recipes, pantry,
        and user preferences.

        :return: a tuple containing the list of selected recipe indices for the meal plan and a placeholder score (0.0)
            since this planner does not perform explicit optimisation
        :rtype: tuple[list[int], float]
        """

        response = self.llm_client.responses.create(model=self.model_name, input=self.prompt)

        raw_meal_plan = response.output[0].content[0].text
        self.best_meal_plan = json.loads(raw_meal_plan)["meal_plan"]

        assert self._assert_meal_plan_length(), "LLM-generated meal plan does not have the expected number of recipes"
        assert self._assert_no_new_recipes(), (
            "LLM-generated meal plan contains recipe indices that are out of bounds of the provided recipe list"
        )

        return self.best_meal_plan, 0.0

    def _assert_no_new_recipes(self) -> bool:
        """
        Asserts that the meal plan generated by the LLM only contains recipes that were provided in the input prompt,
        and does not contain any new or modified recipes.

        :return: True if all recipes in the meal plan are from the original list, False if any new or modified recipes
            are detected
        :rtype: bool
        """

        return all(0 <= index < len(self.recipes) for index in self.best_meal_plan)

    def _assert_meal_plan_length(self, expected_length: int = 21) -> bool:
        """
        Asserts that the meal plan generated by the LLM has the expected number of recipes (e.g. 21 for a 7-day plan
        with 3 meals per day)

        :param expected_length: the expected number of recipes in the meal plan (default = 21)
        :type expected_length: int
        :return: True if the meal plan has the expected length, False otherwise
        :rtype: bool
        """

        return len(self.best_meal_plan) == expected_length
